<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>OmniPos.Desktop</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OmniPos.Server\OmniPos.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Photino.NET" Version="3.1.18" />
  </ItemGroup>
</Project>
